version: '2'
services:
  geth:
    image: dltdojo/geth:1.6.7
    command: ./testrpc.sh
    ports:
        - "8545:8545"  
  db:
    image: mariadb:10.1
    environment:
      - MYSQL_ROOT_PASSWORD=root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
    ports:
        - "8088:80"
