FROM hyperledger/fabric-ca:x86_64-1.0.0
# hyperledger/fabric-baseimage: https://github.com/hyperledger/fabric-baseimage
# DOCKER_BASE_x86_64=ubuntu:xenial https://github.com/hyperledger/fabric-baseimage/blob/master/Makefile#L23
# hyperledger/fabric-ca:x86_64-1.0.0 https://github.com/hyperledger/fabric-ca/blob/release/Makefile#L103
RUN apt-get update && apt-get install -y curl bash jq