version: '2'
services:
  ethnode1:
    image: dltdojo/ethnode:6.a.2
    command: /opt/geth/start.sh
  ethnode2:
    image: dltdojo/ethnode:6.a.2
    command: /opt/geth/testrpc.sh
  truffle:
    image: dltdojo/ethnode:6.a.2
    command: tail -f /dev/null