version: '2'
services:
  node1:
    image: ipfs/go-ipfs
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
  node2:
    image: ipfs/go-ipfs
    ports:
      - "4101:4001"
      - "5101:5001"
      - "8180:8080"
  cpeer1:
    build: peer1
    ports:
      - "4801:4001"
      - "5801:5001"
      - "8880:8080"
  cpeer2:
    build: peer2
    ports:
      - "4901:4001"
      - "5901:5001"
      - "8980:8080"