version: '2'
services:
  geth:
    image: dltdojo/geth:1.6.7
    ports:
        - "8545:8545"
  testrpc:
    image: dltdojo/geth:1.6.7
    command: ./testrpc.sh
    ports:
        - "8545:8545"
  solidity:
    image: dltdojo/browser-solidity
    ports:
        - "8080:8080"